### ISSUE TITLE
Relative path issue with 1.10.x

### ISSUE THREAD

**Issue by mfikes** [omcljs/ambly#127]
```
$ clj -m cljs.main -re ambly

[1] ambly on Linda’s iMac

[R] Refresh

Choice: 1

Connecting to ambly on Linda’s iMac ...

Exception in thread "main" java.lang.IllegalArgumentException: /var/folders/gx/nymj3l7x4zq3gxb97v2zwzb40000gn/T/out7047651953769894382311518056389527/cljs/core.js is not a relative path
	at clojure.java.io$as_relative_path.invokeStatic(io.clj:414)
	at clojure.java.io$file.invokeStatic(io.clj:426)
	at clojure.java.io$file.invoke(io.clj:418)
	at cljs.closure$compile_from_jar.invokeStatic(closure.clj:599)
	at cljs.closure$compile_from_jar.invoke(closure.clj:595)
	at cljs.closure$fn__4984.invokeStatic(closure.clj:648)
	at cljs.closure$fn__4984.invoke(closure.clj:632)
	at cljs.closure$fn__4911$G__4904__4918.invoke(closure.clj:511)
	at cljs.closure$compile.invokeStatic(closure.clj:547)
	at cljs.closure$compile.invoke(closure.clj:544)
	at ambly.core$setup.invokeStatic(core.clj:533)
	at ambly.core$setup.invoke(core.clj:512)
	at ambly.core.JscEnv._setup(core.clj:638)
	at cljs.repl$repl_STAR_$fn__6483.invoke(repl.cljc:919)
	at cljs.compiler$with_core_cljs.invokeStatic(compiler.cljc:1285)
	at cljs.compiler$with_core_cljs.invoke(compiler.cljc:1274)
	at cljs.repl$repl_STAR_.invokeStatic(repl.cljc:917)
	at cljs.repl$repl_STAR_.invoke(repl.cljc:832)
	at cljs.cli$repl_opt.invokeStatic(cli.clj:258)
	at cljs.cli$repl_opt.invoke(cli.clj:247)
	at cljs.cli$main.invokeStatic(cli.clj:577)
	at cljs.cli$main.doInvoke(cli.clj:564)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$apply.invoke(core.clj:652)
	at cljs.main$_main.invokeStatic(main.clj:61)
	at cljs.main$_main.doInvoke(main.clj:52)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.core$apply.invokeStatic(core.clj:657)
	at clojure.main$main_opt.invokeStatic(main.clj:317)
	at clojure.main$main_opt.invoke(main.clj:313)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
```

Workaround:

```
clj -m cljs.main -d out -re ambly -r
```

**Comment by mfikes** [comment]
Fixed https://github.com/mfikes/ambly/commit/1cfaa6908cb1e6825db40d6abcfa04c2d72b79f4
