### ISSUE TITLE
load-file with Ambly in Cursive fails

### ISSUE THREAD

**Issue by mfikes** [omcljs/ambly#64]
```
ClojureScript:cljs.user> (load-file "/Users/mfikes/Documents/Projects/ambly/Clojure/src/foo/bar.cljs")
java.lang.IllegalArgumentException: No implementation of method: :make-reader of protocol: #'clojure.java.io/IOFactory found for class: nil
    at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:544)
    at clojure.java.io$fn__8628$G__8610__8635.invoke(io.clj:69)
    at clojure.java.io$reader.doInvoke(io.clj:102)
    at clojure.lang.RestFn.invoke(RestFn.java:410)
    at cljs.analyzer$forms_seq.invoke(analyzer.clj:1957)
    at cljs.analyzer$parse_ns$fn__1985.invoke(analyzer.clj:2011)
    at cljs.analyzer$parse_ns.invoke(analyzer.clj:1998)
    at cljs.analyzer$parse_ns.invoke(analyzer.clj:1989)
    at cljs.closure$src_file__GT_target_file.invoke(closure.clj:1568)
    at cljs.closure$src_file__GT_target_file.invoke(closure.clj:1563)
    at cljs.repl$load_file.invoke(repl.clj:462)
    at cljs.repl$fn__3959$self__3961.invoke(repl.clj:535)
    at cljs.repl$repl_STAR_$read_eval_print__4024.invoke(repl.clj:725)
    at cljs.repl$repl_STAR_$fn__4030$fn__4035.invoke(repl.clj:767)
    at cljs.repl$repl_STAR_$fn__4030.invoke(repl.clj:766)
    at cljs.compiler$with_core_cljs.invoke(compiler.clj:946)
    at cljs.repl$repl_STAR_.invoke(repl.clj:729)
    at user$eval4248.invoke(NO_SOURCE_FILE:4)
    at clojure.lang.Compiler.eval(Compiler.java:6703)
    at clojure.lang.Compiler.eval(Compiler.java:6666)
    at clojure.core$eval.invoke(core.clj:2927)
    at clojure.main$repl$read_eval_print__6625$fn__6628.invoke(main.clj:239)
    at clojure.main$repl$read_eval_print__6625.invoke(main.clj:239)
    at clojure.main$repl$fn__6634.invoke(main.clj:257)
    at clojure.main$repl.doInvoke(main.clj:257)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.main$repl_opt.invoke(main.clj:323)
    at clojure.main$main.doInvoke(main.clj:420)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.lang.Var.invoke(Var.java:379)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.Var.applyTo(Var.java:700)
    at clojure.main.main(main.java:37)
```

**Comment by mfikes** [comment]
Initially saw this in Cursive, but it happens in terminal (script/jscrepljs):

```
orion:Clojure mfikes$ script/jscrepljs 

[1] Ambly Demo on iPhone Simulator (orion-fikesfarm-com)

[R] Refresh

Choice: 1

Connecting to Ambly Demo on iPhone Simulator (orion-fikesfarm-com) ...

To quit, type: :cljs/quit
ClojureScript:cljs.user> (load-file "/Users/mfikes/Documents/Projects/ambly/Clojure/src/foo/bar.cljs")
java.lang.IllegalArgumentException: No implementation of method: :make-reader of protocol: #'clojure.java.io/IOFactory found for class: nil
    at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:544)
    at clojure.java.io$fn__8628$G__8610__8635.invoke(io.clj:69)
    at clojure.java.io$reader.doInvoke(io.clj:102)
    at clojure.lang.RestFn.invoke(RestFn.java:410)
    at cljs.analyzer$forms_seq.invoke(analyzer.clj:1957)
    at cljs.analyzer$parse_ns$fn__2002.invoke(analyzer.clj:2011)
    at cljs.analyzer$parse_ns.invoke(analyzer.clj:1998)
    at cljs.analyzer$parse_ns.invoke(analyzer.clj:1989)
    at cljs.closure$src_file__GT_target_file.invoke(closure.clj:1568)
    at cljs.closure$src_file__GT_target_file.invoke(closure.clj:1563)
    at cljs.repl$load_file.invoke(repl.clj:462)
    at cljs.repl$fn__3976$self__3978.invoke(repl.clj:535)
    at cljs.repl$repl_STAR_$read_eval_print__4041.invoke(repl.clj:725)
    at cljs.repl$repl_STAR_$fn__4047$fn__4052.invoke(repl.clj:767)
    at cljs.repl$repl_STAR_$fn__4047.invoke(repl.clj:766)
    at cljs.compiler$with_core_cljs.invoke(compiler.clj:946)
    at cljs.repl$repl_STAR_.invoke(repl.clj:729)
    at user$eval4267.invoke(form-init1350491148343590286.clj:3)
    at clojure.lang.Compiler.eval(Compiler.java:6703)
    at clojure.lang.Compiler.eval(Compiler.java:6666)
    at clojure.core$eval.invoke(core.clj:2927)
    at clojure.main$eval_opt.invoke(main.clj:288)
    at clojure.main$initialize.invoke(main.clj:307)
    at clojure.main$null_opt.invoke(main.clj:342)
    at clojure.main$main.doInvoke(main.clj:420)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:383)
    at clojure.lang.AFn.applyToHelper(AFn.java:156)
    at clojure.lang.Var.applyTo(Var.java:700)
    at clojure.main.main(main.java:37)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
    at clojure.lang.Reflector.invokeStaticMethod(Reflector.java:207)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
    at clojure.lang.Reflector.invokeStaticMethod(Reflector.java:207)
    at user$eval5.invoke(form-init1350491148343590286.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6703)
    at clojure.lang.Compiler.eval(Compiler.java:6693)
    at clojure.lang.Compiler.load(Compiler.java:7130)
    at clojure.lang.Compiler.loadFile(Compiler.java:7086)
    at clojure.main$load_script.invoke(main.clj:274)
    at clojure.main$init_opt.invoke(main.clj:279)
    at clojure.main$initialize.invoke(main.clj:307)
    at clojure.main$null_opt.invoke(main.clj:342)
    at clojure.main$main.doInvoke(main.clj:420)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:383)
    at clojure.lang.AFn.applyToHelper(AFn.java:156)
    at clojure.lang.Var.applyTo(Var.java:700)
    at clojure.main.main(main.java:37)
```

**Comment by mfikes** [comment]
This could actually be a ClojureScript issue: http://dev.clojure.org/jira/browse/CLJS-1156
