### ISSUE TITLE
Fails with large response

### ISSUE THREAD

**Issue by mfikes** [omcljs/ambly#8]
```
ClojureScript:cljs.user> (range 0 100000)
java.io.EOFException: JSON error (end-of-file inside string)
    at clojure.data.json$read_quoted_string.invoke(json.clj:137)
    at clojure.data.json$_read.invoke(json.clj:193)
    at clojure.data.json$read_object.invoke(json.clj:93)
    at clojure.data.json$_read.invoke(json.clj:218)
    at clojure.data.json$read.doInvoke(json.clj:270)
    at clojure.lang.RestFn.applyTo(RestFn.java:139)
    at clojure.core$apply.invoke(core.clj:626)
    at clojure.data.json$read_str.doInvoke(json.clj:276)
    at clojure.lang.RestFn.invoke(RestFn.java:439)
    at ambly.repl.jsc$jsc_eval.invoke(jsc.clj:48)
    at ambly.repl.jsc.JscEnv._evaluate(jsc.clj:141)
    at cljs.repl$evaluate_form.invoke(repl.clj:205)
    at cljs.repl$evaluate_form.invoke(repl.clj:167)
    at cljs.repl$eval_and_print.invoke(repl.clj:258)
    at cljs.repl$repl_STAR_.invoke(repl.clj:422)
    at user$eval3590.invoke(form-init6893156465712411744.clj:4)
    at clojure.lang.Compiler.eval(Compiler.java:6703)
    at clojure.lang.Compiler.eval(Compiler.java:6666)
    at clojure.core$eval.invoke(core.clj:2927)
    at clojure.main$repl$read_eval_print__6625$fn__6628.invoke(main.clj:239)
    at clojure.main$repl$read_eval_print__6625.invoke(main.clj:239)
    at clojure.main$repl$fn__6634.invoke(main.clj:257)
    at clojure.main$repl.doInvoke(main.clj:257)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.main$repl_opt.invoke(main.clj:323)
    at clojure.main$main.doInvoke(main.clj:421)
    at clojure.lang.RestFn.invoke(RestFn.java:397)
    at clojure.lang.Var.invoke(Var.java:375)
    at clojure.lang.AFn.applyToHelper(AFn.java:152)
    at clojure.lang.Var.applyTo(Var.java:700)
    at clojure.main.main(main.java:37)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
    at clojure.lang.Reflector.invokeStaticMethod(Reflector.java:207)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
    at clojure.lang.Reflector.invokeStaticMethod(Reflector.java:207)
    at user$eval5.invoke(form-init6893156465712411744.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6703)
    at clojure.lang.Compiler.eval(Compiler.java:6693)
    at clojure.lang.Compiler.load(Compiler.java:7130)
    at clojure.lang.Compiler.loadFile(Compiler.java:7086)
    at clojure.main$load_script.invoke(main.clj:274)
    at clojure.main$init_opt.invoke(main.clj:279)
    at clojure.main$initialize.invoke(main.clj:307)
    at clojure.main$null_opt.invoke(main.clj:342)
    at clojure.main$main.doInvoke(main.clj:420)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:383)
    at clojure.lang.AFn.applyToHelper(AFn.java:156)
    at clojure.lang.Var.applyTo(Var.java:700)
    at clojure.main.main(main.java:37)
java.io.EOFException: JSON error (end-of-file inside string)
nil
```

**Comment by mfikes** [comment]
Probably just need some flow control on Obj-C side. With some extra logging, get this:

```
2015-02-04 16:07:19.548 Ambly Demo[5445:134097] Failed to stream result back to REPL! Written=261676 Expected=588922
```
